// <auto-generated />
using System;
using Galaxy.GestionGuarderia.AccesDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Galaxy.GestionGuarderia.AccesDatos.Migrations
{
    [DbContext(typeof(BDGuarderiaDbContext))]
    [Migration("20241123184310_NuevaMigracion")]
    partial class NuevaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Galaxy.GestionGuarderia.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 11, 23, 18, 43, 9, 727, DateTimeKind.Utc).AddTicks(6217),
                            Nombre = "Sala menos de 1 año"
                        },
                        new
                        {
                            Id = 2,
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 11, 23, 18, 43, 9, 727, DateTimeKind.Utc).AddTicks(7075),
                            Nombre = "Sala 1 a 2 años"
                        },
                        new
                        {
                            Id = 3,
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 11, 23, 18, 43, 9, 727, DateTimeKind.Utc).AddTicks(7163),
                            Nombre = "Sala 2 a 3 años"
                        },
                        new
                        {
                            Id = 4,
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 11, 23, 18, 43, 9, 727, DateTimeKind.Utc).AddTicks(7165),
                            Nombre = "Sala jardin"
                        },
                        new
                        {
                            Id = 5,
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 11, 23, 18, 43, 9, 727, DateTimeKind.Utc).AddTicks(7166),
                            Nombre = "Sala multiuso"
                        },
                        new
                        {
                            Id = 6,
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 11, 23, 18, 43, 9, 727, DateTimeKind.Utc).AddTicks(7176),
                            Nombre = "Comedor"
                        },
                        new
                        {
                            Id = 7,
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 11, 23, 18, 43, 9, 727, DateTimeKind.Utc).AddTicks(7178),
                            Nombre = "Sala descanso"
                        },
                        new
                        {
                            Id = 8,
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 11, 23, 18, 43, 9, 727, DateTimeKind.Utc).AddTicks(7179),
                            Nombre = "Sala de espera"
                        },
                        new
                        {
                            Id = 9,
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 11, 23, 18, 43, 9, 727, DateTimeKind.Utc).AddTicks(7180),
                            Nombre = "Administracion"
                        });
                });

            modelBuilder.Entity("Galaxy.GestionGuarderia.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Celular")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Distrito")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Galaxy.GestionGuarderia.Entidades.Cuidador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("NroDocumento");

                    b.ToTable("Cuidador");
                });

            modelBuilder.Entity("Galaxy.GestionGuarderia.Entidades.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<int>("Situacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteID");

                    b.HasIndex("ModuloId");

                    b.ToTable("Inscripcion");
                });

            modelBuilder.Entity("Galaxy.GestionGuarderia.Entidades.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("CuidadorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PortadaURL")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Situacion")
                        .HasColumnType("int");

                    b.Property<string>("TemarioURL")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CuidadorId");

                    b.ToTable("Modulo");
                });

            modelBuilder.Entity("Galaxy.GestionGuarderia.Entidades.Cuidador", b =>
                {
                    b.HasOne("Galaxy.GestionGuarderia.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Galaxy.GestionGuarderia.Entidades.Inscripcion", b =>
                {
                    b.HasOne("Galaxy.GestionGuarderia.Entidades.Cliente", "Cliente")
                        .WithMany("Inscripciones")
                        .HasForeignKey("ClienteID")
                        .IsRequired();

                    b.HasOne("Galaxy.GestionGuarderia.Entidades.Modulo", "Modulo")
                        .WithMany("Inscripciones")
                        .HasForeignKey("ModuloId")
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Galaxy.GestionGuarderia.Entidades.Modulo", b =>
                {
                    b.HasOne("Galaxy.GestionGuarderia.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .IsRequired();

                    b.HasOne("Galaxy.GestionGuarderia.Entidades.Cuidador", "Cuidador")
                        .WithMany()
                        .HasForeignKey("CuidadorId")
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cuidador");
                });

            modelBuilder.Entity("Galaxy.GestionGuarderia.Entidades.Cliente", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Galaxy.GestionGuarderia.Entidades.Modulo", b =>
                {
                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
